import 'package:swipezone/repositories/location_repository.dart';
import 'package:swipezone/repositories/models/categories.dart';
import 'package:swipezone/repositories/models/localization.dart';
import 'package:swipezone/repositories/models/location.dart';
//import 'package:http/http.dart' as http; // Removed as image verification is no longer needed

class ILocationRepository implements LocationRepository {
  @override
  Future<List<Location>> getLocations() async {
    List<Location> locations = [
      Location(
        nom: "Tour Eiffel",
        description: "Emblème de Paris, cette tour en fer puddlé de 324 mètres de hauteur est l'un des sites les plus visités au monde.",
        imagePath: "lib/assets/images/tour_eiffel.png",
        category: Categories.Tower,
        localization: Localization("Champ de Mars, 5 Avenue Anatole France, 75007 Paris", 48.8584, 2.2945),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Louvre",
        description: "Le plus grand musée d'art du monde, abritant la Joconde.",
        imagePath: "lib/assets/images/musee_louvre.png",
        category: Categories.Museum,
        localization: Localization("Rue de Rivoli, 75001 Paris", 48.8606, 2.3376),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cathédrale Notre-Dame",
        description: "La cathédrale gothique Notre-Dame est située sur l'île de la Cité.",
        imagePath: "lib/assets/images/notre_dame.png",
        category: Categories.Church,
        localization: Localization("6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris", 48.8529, 2.3508),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Arc de Triomphe",
        description: "Construit pour honorer les victoires de Napoléon, il est situé sur la place de l'Étoile.",
        imagePath: "lib/assets/images/arc_de_triomphe.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place Charles de Gaulle, 75008 Paris", 48.8738, 2.295),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Sacré-Cœur",
        description: "La basilique du Sacré-Cœur est un symbole religieux de Montmartre.",
        imagePath: "lib/assets/images/sacre_coeur.png",
        category: Categories.Church,
        localization: Localization("35 Rue du Chevalier de la Barre, 75018 Paris", 48.8867, 2.3431),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Panthéon",
        description: "Le Panthéon est un mausolée pour les grandes figures françaises.",
        imagePath: "lib/assets/images/pantheon_paris.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place du Panthéon, 75005 Paris", 48.8462, 2.3449),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Place de la Concorde",
        description: "La plus grande place de Paris, connue pour son obélisque et ses fontaines.",
        imagePath: "lib/assets/images/place_de_la_concorde.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place de la Concorde, 75008 Paris", 48.8656, 2.3212),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Palais Garnier",
        description: "L'Opéra Garnier est une somptueuse salle de spectacle datant du XIXe siècle.",
        imagePath: "lib/assets/images/palais_garnier.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place de l'Opéra, 75009 Paris", 48.8719, 2.3316),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Jardin des Tuileries",
        description: "Le jardin des Tuileries est un jardin public historique situé près du Louvre.",
        imagePath: "lib/assets/images/jardin_des_tuileries.png",
        category: Categories.Park,
        localization: Localization("113 Rue de Rivoli, 75001 Paris", 48.8636, 2.3276),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Pont Alexandre III",
        description: "Ce pont richement orné relie les Champs-Élysées et les Invalides.",
        imagePath: "lib/assets/images/pont_alexandre_III.png",
        category: Categories.HistoricalSite,
        localization: Localization("Pont Alexandre III, 75008 Paris", 48.8654, 2.3131),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée d'Orsay",
        description: "Musée d'art installé dans une ancienne gare, spécialisé dans l'art du XIXe siècle.",
        imagePath: "lib/assets/images/musee_orsay.png",
        category: Categories.Museum,
        localization: Localization("1 Rue de la Légion d'Honneur, 75007 Paris", 48.8600, 2.3266),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Centre Pompidou",
        description: "Centre d'art moderne et contemporain reconnaissable à son architecture unique.",
        imagePath: "lib/assets/images/centre_pompidou.png",
        category: Categories.Museum,
        localization: Localization("Place Georges-Pompidou, 75004 Paris", 48.8606, 2.3522),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Sainte-Chapelle",
        description: "Chapelle gothique du XIIIe siècle célèbre pour ses magnifiques vitraux.",
        imagePath: "lib/assets/images/sainte_chapelle.png",
        category: Categories.Church,
        localization: Localization("8 Boulevard du Palais, 75001 Paris", 48.8554, 2.3451),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Rodin",
        description: "Musée dédié au sculpteur Auguste Rodin, situé dans un hôtel particulier avec jardin.",
        imagePath: "lib/assets/images/musee_rodin.png",
        category: Categories.Museum,
        localization: Localization("77 Rue de Varenne, 75007 Paris", 48.8555, 2.3154),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Jardin du Luxembourg",
        description: "Grand jardin public inspiré des jardins italiens, populaire auprès des Parisiens.",
        imagePath: "lib/assets/images/jardin_luxembourg.png",
        category: Categories.Park,
        localization: Localization("75006 Paris", 48.8462, 2.3372),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Moulin Rouge",
        description: "Célèbre cabaret parisien connu pour ses spectacles de French Cancan.",
        imagePath: "lib/assets/images/moulin_rouge.png",
        category: Categories.HistoricalSite,
        localization: Localization("82 Boulevard de Clichy, 75018 Paris", 48.8842, 2.3322),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Les Invalides",
        description: "Complexe de bâtiments abritant des musées et monuments liés à l'histoire militaire de la France.",
        imagePath: "lib/assets/images/les_invalides.png",
        category: Categories.Museum,
        localization: Localization("129 Rue de Grenelle, 75007 Paris", 48.8559, 2.3127),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Palais de l'Élysée",
        description: "Résidence officielle du président de la République française.",
        imagePath: "lib/assets/images/palais_elysee.png",
        category: Categories.HistoricalSite,
        localization: Localization("55 Rue du Faubourg Saint-Honoré, 75008 Paris", 48.8706, 2.3165),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Palais-Bourbon",
        description: "Siège de l'Assemblée nationale française.",
        imagePath: "lib/assets/images/palais_bourbon.png",
        category: Categories.HistoricalSite,
        localization: Localization("126 Rue de l'Université, 75007 Paris", 48.8620, 2.3181),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Palais du Luxembourg",
        description: "Siège du Sénat français.",
        imagePath: "lib/assets/images/palais_luxembourg.png",
        category: Categories.HistoricalSite,
        localization: Localization("15 Rue de Vaugirard, 75006 Paris", 48.8462, 2.3371),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Place des Vosges",
        description: "La plus ancienne place de Paris.",
        imagePath: "lib/assets/images/place_des_vosges.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place des Vosges, 75004 Paris", 48.8559, 2.3659),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Carnavalet",
        description: "Musée dédié à l'histoire de Paris.",
        imagePath: "lib/assets/images/musee_carnavalet.png",
        category: Categories.Museum,
        localization: Localization("23 Rue de Sévigné, 75003 Paris", 48.8570, 2.3624),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Picasso",
        description: "Musée dédié à l'œuvre du célèbre peintre Pablo Picasso.",
        imagePath: "lib/assets/images/musee_picasso.png",
        category: Categories.Museum,
        localization: Localization("5 Rue de Thorigny, 75003 Paris", 48.8643, 2.3656),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Château de Vincennes",
        description: "Un château médiéval fortifié situé à l'est de Paris.",
        imagePath: "lib/assets/images/chateau_vincennes.png",
        category: Categories.HistoricalSite,
        localization: Localization("Avenue de Paris, 94300 Vincennes", 48.8502, 2.4365),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Chasse et de la Nature",
        description: "Musée unique dédié à l'histoire de la chasse et de la nature.",
        imagePath: "lib/assets/images/musee_chasse_et_nature.png",
        category: Categories.Museum,
        localization: Localization("62 Rue des Archives, 75003 Paris", 48.8583, 2.3647),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Institut du Monde Arabe",
        description: "Un centre culturel dédié à la culture arabe et à l'art du monde arabe.",
        imagePath: "lib/assets/images/institut_monde_arabe.png",
        category: Categories.Museum,
        localization: Localization("1 Rue des Fossés Saint-Bernard, 75005 Paris", 48.8495, 2.3610),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Monnaie de Paris",
        description: "Musée consacré à l'histoire de la monnaie et à la frappe des pièces de monnaie.",
        imagePath: "lib/assets/images/musee_monnaie_paris.png",
        category: Categories.Museum,
        localization: Localization("11 Quai de Conti, 75006 Paris", 48.8525, 2.3391),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de l'Orangerie",
        description: "Musée abritant les célèbres Nymphéas de Claude Monet et d'autres œuvres impressionnistes.",
        imagePath: "lib/assets/images/musee_orangerie.png",
        category: Categories.Museum,
        localization: Localization("Jardin des Tuileries, 75001 Paris", 48.8638, 2.3215),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Marmottan Monet",
        description: "Musée d'art impressionniste, célèbre pour ses collections de Claude Monet.",
        imagePath: "lib/assets/images/musee_marmottan_monet.png",
        category: Categories.Museum,
        localization: Localization("2 Rue Louis Boilly, 75016 Paris", 48.8622, 2.2776),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Jacquemart-André",
        description: "Hôtel particulier transformé en musée, présentant une collection d'art du 18e siècle.",
        imagePath: "lib/assets/images/musee_jacquemart_andre.png",
        category: Categories.Museum,
        localization: Localization("158 Boulevard Haussmann, 75008 Paris", 48.8756, 2.3119),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Guimet",
        description: "Musée national des arts asiatiques.",
        imagePath: "lib/assets/images/musee_guimet.png",
        category: Categories.Museum,
        localization: Localization("6 Place d'Iéna, 75116 Paris", 48.8651, 2.2936),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de Cluny",
        description: "Musée national du Moyen Âge.",
        imagePath: "lib/assets/images/musee_cluny.png",
        category: Categories.Museum,
        localization: Localization("28 Rue du Sommerard, 75005 Paris", 48.8505, 2.3443),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée du quai Branly - Jacques Chirac",
        description: "Musée des arts et civilisations d'Afrique, d'Asie, d'Océanie et des Amériques.",
        imagePath: "lib/assets/images/musee_quai_branly.png",
        category: Categories.Museum,
        localization: Localization("37 Quai Branly, 75007 Paris", 48.8608, 2.2973),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Nissim de Camondo",
        description: "Musée d'arts décoratifs du XVIIIe siècle.",
        imagePath: "lib/assets/images/musee_nissim_de_camondo.png",
        category: Categories.Museum,
        localization: Localization("63 Rue de Monceau, 75008 Paris", 48.8796, 2.3149),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Grévin",
        description: "Célèbre musée de cire présentant des personnalités historiques et contemporaines.",
        imagePath: "lib/assets/images/musee_grevin.png",
        category: Categories.Museum,
        localization: Localization("10 Boulevard Montmartre, 75009 Paris", 48.8721, 2.3426),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Vie Romantique",
        description: "Maison-musée dédiée à l'époque romantique du 19e siècle.",
        imagePath: "lib/assets/images/musee_vie_romantique.png",
        category: Categories.Museum,
        localization: Localization("16 Rue Chaptal, 75009 Paris", 48.8822, 2.3279),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée des Égouts de Paris",
        description: "Musée souterrain présentant l'histoire et le fonctionnement des égouts parisiens.",
        imagePath: "lib/assets/images/musee_egouts_de_paris.png",
        category: Categories.Museum,
        localization: Localization("Pont de l'Alma, 75007 Paris", 48.8636, 2.3017),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée du Parfum",
        description: "Musée dédié à l'histoire et à l'art de la parfumerie.",
        imagePath: "lib/assets/images/musee_parfum.png",
        category: Categories.Museum,
        localization: Localization("9 Rue Scribe, 75009 Paris", 48.8714, 2.3295),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Magie",
        description: "Musée consacré à l'art de la magie et de l'illusion.",
        imagePath: "lib/assets/images/musee_magie.png",
        category: Categories.Museum,
        localization: Localization("11 Rue Saint-Paul, 75004 Paris", 48.8535, 2.3665),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée des Arts Forains",
        description: "Musée privé consacré aux arts du spectacle et aux manèges anciens.",
        imagePath: "lib/assets/images/musee_arts_forains.png",
        category: Categories.Museum,
        localization: Localization("53 Avenue des Terroirs de France, 75012 Paris", 48.8336, 2.3867),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Bourdelle",
        description: "Musée dédié à l'œuvre du sculpteur Antoine Bourdelle.",
        imagePath: "lib/assets/images/musee_bourdelle.png",
        category: Categories.Museum,
        localization: Localization("18 Rue Antoine Bourdelle, 75015 Paris", 48.8425, 2.3214),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Zadkine",
        description: "Atelier-musée du sculpteur Ossip Zadkine.",
        imagePath: "lib/assets/images/musee_zadkine.png",
        category: Categories.Museum,
        localization: Localization("100 bis Rue d'Assas, 75006 Paris", 48.8424, 2.3304),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Cognacq-Jay",
        description: "Musée d'art du XVIIIe siècle.",
        imagePath: "lib/assets/images/musee_cognac_jay.png",
        category: Categories.Museum,
        localization: Localization("8 Rue Elzévir, 75003 Paris", 48.8586, 2.3625),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Musique",
        description: "Musée présentant une collection d'instruments de musique et l'histoire de la musique.",
        imagePath: "lib/assets/images/musee_musique.png",
        category: Categories.Museum,
        localization: Localization("221 Avenue Jean Jaurès, 75019 Paris", 48.8890, 2.3935),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de l'Air et de l'Espace",
        description: "Musée consacré à l'aéronautique et à l'espace.",
        imagePath: "lib/assets/images/musee_air_espace.png",
        category: Categories.Museum,
        localization: Localization("Aéroport de Paris-Le Bourget, 93350 Le Bourget", 48.9472, 2.4372),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Contrefaçon",
        description: "Musée unique dédié à l'histoire et aux enjeux de la contrefaçon.",
        imagePath: "lib/assets/images/musee_contrefacon.png",
        category: Categories.Museum,
        localization: Localization("16 Rue de la Faisanderie, 75116 Paris", 48.8672, 2.2778),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de l'Éventail",
        description: "Petit musée spécialisé dans l'art et l'histoire des éventails.",
        imagePath: "lib/assets/images/musee_eventail.png",
        category: Categories.Museum,
        localization: Localization("2 Boulevard de Strasbourg, 75010 Paris", 48.8697, 2.3553),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Préfecture de Police",
        description: "Musée dédié à l'histoire de la police et de la sécurité publique.",
        imagePath: "lib/assets/images/musee_prefecture_police.png",
        category: Categories.Museum,
        localization: Localization("4 Rue de la Montagne Sainte-Geneviève, 75005 Paris", 48.8482, 2.3477),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée des Arts et Métiers",
        description: "Musée présentant l'histoire des inventions, des technologies et des sciences.",
        imagePath: "lib/assets/images/musee_arts_et_metiers.png",
        category: Categories.Museum,
        localization: Localization("60 Rue Réaumur, 75003 Paris", 48.8670, 2.3582),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de l'Opéra",
        description: "Musée consacré à l'histoire de l'Opéra Garnier et à l'art lyrique.",
        imagePath: "lib/assets/images/musee_opera.png",
        category: Categories.Museum,
        localization: Localization("8 Rue Scribe, 75009 Paris", 48.8720, 2.3319),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Poupée",
        description: "Musée consacré aux poupées et aux jouets anciens.",
        imagePath: "lib/assets/images/musee_poupee.png",
        category: Categories.Museum,
        localization: Localization("Impasse Berthaud, 75003 Paris", 48.8601, 2.3539),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cité de la Musique",
        description: "Centre culturel dédié à la musique, avec des concerts et des expositions.",
        imagePath: "lib/assets/images/cite_musique.png",
        category: Categories.Museum,
        localization: Localization("221 Avenue Jean-Jaurès, 75019 Paris", 48.8877, 2.3945),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée du Chocolat",
        description: "Musée interactif sur l'histoire du chocolat et des techniques de fabrication.",
        imagePath: "lib/assets/images/musee_chocolat.png",
        category: Categories.Museum,
        localization: Localization("28 Boulevard de Bonne Nouvelle, 75010 Paris", 48.8690, 2.3470),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Santé des Armées",
        description: "Musée présentant l'histoire de la médecine militaire et des soins de santé dans les armées.",
        imagePath: "lib/assets/images/musee_sante_armees.png",
        category: Categories.Museum,
        localization: Localization("1 Place Alphonse Laveran, 75005 Paris", 48.8410, 2.3414),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Curie",
        description: "Musée dédié à l'histoire des découvertes scientifiques de Marie Curie.",
        imagePath: "lib/assets/images/musee_curie.png",
        category: Categories.Museum,
        localization: Localization("1 Rue Pierre et Marie Curie, 75005 Paris", 48.8447, 2.3449),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée du Luxembourg",
        description: "Musée exposant des œuvres d'art classique et moderne.",
        imagePath: "lib/assets/images/musee_luxembourg.png",
        category: Categories.Museum,
        localization: Localization("19 Rue de Vaugirard, 75006 Paris", 48.8440, 2.3346),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée des Arts Décoratifs",
        description: "Musée dédié à l'art décoratif et aux objets du quotidien.",
        imagePath: "lib/assets/images/musee_arts_decoratifs.png",
        category: Categories.Museum,
        localization: Localization("107 Rue de Rivoli, 75001 Paris", 48.8636, 2.3350),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée du Petit Palais",
        description: "Musée abritant une collection d'art du XIXe siècle.",
        imagePath: "lib/assets/images/musee_petit_palais.png",
        category: Categories.Museum,
        localization: Localization("Avenue Winston Churchill, 75008 Paris", 48.8664, 2.3122),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Cité de l'Architecture et du Patrimoine",
        description: "Musée qui présente l'architecture et le patrimoine de la France.",
        imagePath: "lib/assets/images/musee_architecture_patrimoine.png",
        category: Categories.Museum,
        localization: Localization("1 Place du Trocadéro et du 11 Novembre, 75116 Paris", 48.8637, 2.2901),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Police",
        description: "Musée consacré à l'histoire de la police à travers les siècles.",
        imagePath: "lib/assets/images/musee_prefecture_police.png",
        category: Categories.Museum,
        localization: Localization("4 Rue de la Montagne Sainte-Geneviève, 75005 Paris", 48.8482, 2.3477),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Cernuschi",
        description: "Musée des Arts de l'Asie de la ville de Paris.",
        imagePath: "lib/assets/images/musee_cernuschi.png",
        category: Categories.Museum,
        localization: Localization("7 Avenue Velasquez, 75008 Paris", 48.8794, 2.3122),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de la Vie Romantique",
        description: "Maison-musée dédiée à l'époque romantique du 19e siècle.",
        imagePath: "lib/assets/images/musee_vie_romantique.png",
        category: Categories.Museum,
        localization: Localization("16 Rue Chaptal, 75009 Paris", 48.8822, 2.3279),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée Carnavalet",
        description: "Musée de l'histoire de Paris, de la préhistoire à nos jours.",
        imagePath: "lib/assets/images/musee_carnavalet.png",
        category: Categories.Museum,
        localization: Localization("23 Rue de Sévigné, 75003 Paris", 48.8570, 2.3624),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de Montmartre",
        description: "Musée dédié à l'histoire et à la culture du quartier de Montmartre.",
        imagePath: "lib/assets/images/musee_montmartre.png",
        category: Categories.Museum,
        localization: Localization("12 Rue Cortot, 75018 Paris", 48.8876, 2.3384),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée de l'Homme",
        description: "Musée d'anthropologie situé dans le Palais de Chaillot.",
        imagePath: "lib/assets/images/musee_homme.png",
        category: Categories.Museum,
        localization: Localization("17 Place du Trocadéro, 75116 Paris", 48.8619, 2.2867),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Muséenational Eugène Delacroix",
        description: "Musée dédié au peintre Eugène Delacroix.",
        imagePath: "lib/assets/images/musee_eugene_delacroix.png",
        category: Categories.Museum,
        localization: Localization("6 Rue de Furstenberg, 75006 Paris", 48.8547, 2.3344),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée national Gustave Moreau",
        description:        "Musée consacré à l'œuvre du peintre symboliste Gustave Moreau.",
        imagePath: "lib/assets/images/musee_gustave_moreau.png",
        category: Categories.Museum,
        localization: Localization("14 Rue de la Rochefoucauld, 75009 Paris", 48.8788, 2.3337),
        schedule: null,
        contact: null,
        website: null,
      ),
    ];

    return locations;
  }
}

