import 'package:swipezone/repositories/location_repository.dart';
import 'package:swipezone/repositories/models/categories.dart';
import 'package:swipezone/repositories/models/localization.dart';
import 'package:swipezone/repositories/models/location.dart';

class ILocationRepository implements LocationRepository {
  @override
  Future<List<Location>> getLocations() async {
    List<Location> locations = [
      Location(
        nom: "Eiffel Tower",
        description: "Symbol of Paris, this 324-meter-high puddled iron tower is one of the most visited sites in the world.",
        imagePath: "lib/assets/images/tour_eiffel.png",
        category: Categories.Tower,
        localization: Localization("Champ de Mars, 5 Avenue Anatole France, 75007 Paris", 48.8584, 2.2945),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Louvre",
        description: "The world's largest art museum, home to the Mona Lisa.",
        imagePath: "lib/assets/images/musee_louvre.png",
        category: Categories.Museum,
        localization: Localization("Rue de Rivoli, 75001 Paris", 48.8606, 2.3376),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Notre-Dame Cathedral",
        description: "The Gothic Notre-Dame Cathedral is located on the Île de la Cité.",
        imagePath: "lib/assets/images/notre_dame.png",
        category: Categories.Church,
        localization: Localization("6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris", 48.8529, 2.3508),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Arc de Triomphe",
        description: "Built to honor Napoleon's victories, it is located on the Place de l'Étoile.",
        imagePath: "lib/assets/images/arc_de_triomphe.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place Charles de Gaulle, 75008 Paris", 48.8738, 2.295),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Sacré-Cœur",
        description: "The Sacré-Cœur Basilica is a religious symbol of Montmartre.",
        imagePath: "lib/assets/images/sacre_coeur.png",
        category: Categories.Church,
        localization: Localization("35 Rue du Chevalier de la Barre, 75018 Paris", 48.8867, 2.3431),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Panthéon",
        description: "The Pantheon is a mausoleum for great French figures.",
        imagePath: "lib/assets/images/pantheon_paris.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place du Panthéon, 75005 Paris", 48.8462, 2.3449),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Place de la Concorde",
        description: "The largest square in Paris, known for its obelisk and fountains.",
        imagePath: "lib/assets/images/place_de_la_concorde.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place de la Concorde, 75008 Paris", 48.8656, 2.3212),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Palais Garnier",
        description: "The Opéra Garnier is a sumptuous 19th-century performance hall.",
        imagePath: "lib/assets/images/palais_garnier.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place de l'Opéra, 75009 Paris", 48.8719, 2.3316),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Tuileries Garden",
        description: "The Tuileries Garden is a historic public garden located near the Louvre.",
        imagePath: "lib/assets/images/jardin_des_tuileries.png",
        category: Categories.Park,
        localization: Localization("113 Rue de Rivoli, 75001 Paris", 48.8636, 2.3276),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Pont Alexandre III",
        description: "This richly decorated bridge connects the Champs-Élysées and the Invalides.",
        imagePath: "lib/assets/images/pont_alexandre_III.png",
        category: Categories.HistoricalSite,
        localization: Localization("Pont Alexandre III, 75008 Paris", 48.8654, 2.3131),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Musée d'Orsay",
        description: "Art museum housed in a former railway station, specializing in 19th-century art.",
        imagePath: "lib/assets/images/musee_orsay.png",
        category: Categories.Museum,
        localization: Localization("1 Rue de la Légion d'Honneur, 75007 Paris", 48.8600, 2.3266),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Centre Pompidou",
        description: "Modern and contemporary art center recognizable by its unique architecture.",
        imagePath: "lib/assets/images/centre_pompidou.png",
        category: Categories.Museum,
        localization: Localization("Place Georges-Pompidou, 75004 Paris", 48.8606, 2.3522),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Sainte-Chapelle",
        description: "13th-century Gothic chapel famous for its magnificent stained glass windows.",
        imagePath: "lib/assets/images/sainte_chapelle.png",
        category: Categories.Church,
        localization: Localization("8 Boulevard du Palais, 75001 Paris", 48.8554, 2.3451),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Rodin Museum",
        description: "Museum dedicated to sculptor Auguste Rodin, located in a mansion with a garden.",
        imagePath: "lib/assets/images/musee_rodin.png",
        category: Categories.Museum,
        localization: Localization("77 Rue de Varenne, 75007 Paris", 48.8555, 2.3154),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Luxembourg Garden",
        description: "Large public garden inspired by Italian gardens, popular among Parisians.",
        imagePath: "lib/assets/images/jardin_luxembourg.png",
        category: Categories.Park,
        localization: Localization("75006 Paris", 48.8462, 2.3372),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Moulin Rouge",
        description: "Famous Parisian cabaret known for its French Cancan shows.",
        imagePath: "lib/assets/images/moulin_rouge.png",
        category: Categories.HistoricalSite,
        localization: Localization("82 Boulevard de Clichy, 75018 Paris", 48.8842, 2.3322),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Les Invalides",
        description: "Complex of buildings housing museums and monuments related to France's military history.",
        imagePath: "lib/assets/images/les_invalides.png",
        category: Categories.HistoricalSite,
        localization: Localization("129 Rue de Grenelle, 75007 Paris", 48.8559, 2.3127),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Élysée Palace",
        description: "Official residence of the President of the French Republic.",
        imagePath: "lib/assets/images/palais_elysee.png",
        category: Categories.HistoricalSite,
        localization: Localization("55 Rue du Faubourg Saint-Honoré, 75008 Paris", 48.8706, 2.3165),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Bourbon Palace",
        description: "Seat of the French National Assembly.",
        imagePath: "lib/assets/images/palais_bourbon.png",
        category: Categories.HistoricalSite,
        localization: Localization("126 Rue de l'Université, 75007 Paris", 48.8620, 2.3181),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Luxembourg Palace",
        description: "Seat of the French Senate.",
        imagePath: "lib/assets/images/palais_luxembourg.png",
        category: Categories.HistoricalSite,
        localization: Localization("15 Rue de Vaugirard, 75006 Paris", 48.8462, 2.3371),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Place des Vosges",
        description: "The oldest square in Paris.",
        imagePath: "lib/assets/images/place_des_vosges.png",
        category: Categories.HistoricalSite,
        localization: Localization("Place des Vosges, 75004 Paris", 48.8559, 2.3659),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Carnavalet Museum",
        description: "Museum dedicated to the history of Paris.",
        imagePath: "lib/assets/images/musee_carnavalet.png",
        category: Categories.Museum,
        localization: Localization("23 Rue de Sévigné, 75003 Paris", 48.8570, 2.3624),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Picasso Museum",
        description: "Museum dedicated to the work of famous painter Pablo Picasso.",
        imagePath: "lib/assets/images/musee_picasso.png",
        category: Categories.Museum,
        localization: Localization("5 Rue de Thorigny, 75003 Paris", 48.8643, 2.3656),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Château de Vincennes",
        description: "A fortified medieval castle located east of Paris.",
        imagePath: "lib/assets/images/chateau_vincennes.png",
        category: Categories.HistoricalSite,
        localization: Localization("Avenue de Paris, 94300 Vincennes", 48.8502, 2.4365),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Hunting and Nature",
        description: "Unique museum dedicated to the history of hunting and nature.",
        imagePath: "lib/assets/images/musee_chasse_et_nature.png",
        category: Categories.Museum,
        localization: Localization("62 Rue des Archives, 75003 Paris", 48.8583, 2.3647),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Arab World Institute",
        description: "A cultural center dedicated to Arab culture and art from the Arab world.",
        imagePath: "lib/assets/images/institut_monde_arabe.png",
        category: Categories.Museum,
        localization: Localization("1 Rue des Fossés Saint-Bernard, 75005 Paris", 48.8495, 2.3610),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Paris Mint Museum",
        description: "Museum dedicated to the history of currency and coin minting.",
        imagePath: "lib/assets/images/musee_monnaie_paris.png",
        category: Categories.Museum,
        localization: Localization("11 Quai de Conti, 75006 Paris", 48.8525, 2.3391),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Orangerie Museum",
        description: "Museum housing Claude Monet's famous Water Lilies and other Impressionist works.",
        imagePath: "lib/assets/images/musee_orangerie.png",
        category: Categories.Museum,
        localization: Localization("Jardin des Tuileries, 75001 Paris", 48.8638, 2.3215),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Marmottan Monet Museum",
        description: "Impressionist art museum, famous for its Claude Monet collections.",
        imagePath: "lib/assets/images/musee_marmottan_monet.png",
        category: Categories.Museum,
        localization: Localization("2 Rue Louis Boilly, 75016 Paris", 48.8622, 2.2776),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Jacquemart-André Museum",
        description: "Private mansion turned into a museum, showcasing 18th-century art collection.",
        imagePath: "lib/assets/images/musee_jacquemart_andre.png",
        category: Categories.Museum,
        localization: Localization("158 Boulevard Haussmann, 75008 Paris", 48.8756, 2.3119),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Guimet Museum",
        description: "National Museum of Asian Arts.",
        imagePath: "lib/assets/images/musee_guimet.png",
        category: Categories.Museum,
        localization: Localization("6 Place d'Iéna, 75116 Paris", 48.8651, 2.2936),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cluny Museum",
        description: "National Museum of the Middle Ages.",
        imagePath: "lib/assets/images/musee_cluny.png",
        category: Categories.Museum,
        localization: Localization("28 Rue du Sommerard, 75005 Paris", 48.8505, 2.3443),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Quai Branly Museum - Jacques Chirac",
        description: "Museum of arts and civilizations of Africa, Asia, Oceania, and the Americas.",
        imagePath: "lib/assets/images/musee_quai_branly.png",
        category: Categories.Museum,
        localization: Localization("37 Quai Branly, 75007 Paris", 48.8608, 2.2973),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Nissim de Camondo Museum",
        description: "Museum of 18th-century decorative arts.",
        imagePath: "lib/assets/images/musee_nissim_de_camondo.png",
        category: Categories.Museum,
        localization: Localization("63 Rue de Monceau, 75008 Paris", 48.8796, 2.3149),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Grévin Museum",
        description: "Famous wax museum featuring historical and contemporary personalities.",
        imagePath: "lib/assets/images/musee_grevin.png",
        category: Categories.Museum,
        localization: Localization("10 Boulevard Montmartre, 75009 Paris", 48.8721, 2.3426),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Romantic Life",
        description: "House-museum dedicated to the Romantic era of the 19th century.",
        imagePath: "lib/assets/images/musee_vie_romantique.png",
        category: Categories.Museum,
        localization: Localization("16 Rue Chaptal, 75009 Paris", 48.8822, 2.3279),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Paris Sewer Museum",
        description: "Underground museum showcasing the history and operation of Paris sewers.",
        imagePath: "lib/assets/images/musee_egouts_de_paris.png",
        category: Categories.Museum,
        localization: Localization("Pont de l'Alma, 75007 Paris", 48.8636, 2.3017),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Perfume Museum",
        description: "Museum dedicated to the history and art of perfumery.",
        imagePath: "lib/assets/images/musee_parfum.png",
        category: Categories.Museum,
        localization: Localization("9 Rue Scribe, 75009 Paris", 48.8714, 2.3295),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Magic Museum",
        description: "Museum dedicated to the art of magic and illusion.",
        imagePath: "lib/assets/images/musee_magie.png",
        category: Categories.Museum,
        localization: Localization("11 Rue Saint-Paul, 75004 Paris", 48.8535, 2.3665),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Fairground Arts",
        description: "Private museum dedicated to the performing arts and antique carousels.",
        imagePath: "lib/assets/images/musee_arts_forains.png",
        category: Categories.Museum,
        localization: Localization("53 Avenue des Terroirs de France, 75012 Paris", 48.8336, 2.3867),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Bourdelle Museum",
        description: "Museum dedicated to the work of sculptor Antoine Bourdelle.",
        imagePath: "lib/assets/images/musee_bourdelle.png",
        category: Categories.Museum,
        localization: Localization("18 Rue Antoine Bourdelle, 75015 Paris", 48.8425, 2.3214),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Zadkine Museum",
        description: "Studio-museum of sculptor Ossip Zadkine.",
        imagePath: "lib/assets/images/musee_zadkine.png",
        category: Categories.Museum,
        localization: Localization("100 bis Rue d'Assas, 75006 Paris", 48.8424, 2.3304),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cognacq-Jay Museum",
        description: "18th-century art museum.",
        imagePath: "lib/assets/images/musee_cognac_jay.png",
        category: Categories.Museum,
        localization: Localization("8 Rue Elzévir, 75003 Paris", 48.8586, 2.3625),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Music Museum",
        description: "Museum showcasing a collection of musical instruments and the history of music.",
        imagePath: "lib/assets/images/musee_musique.png",
        category: Categories.Museum,
        localization: Localization("221 Avenue Jean Jaurès, 75019 Paris", 48.8890, 2.3935),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Air and Space Museum",
        description: "Museum dedicated to aeronautics and space.",
        imagePath: "lib/assets/images/musee_air_espace.png",
        category: Categories.Museum,
        localization: Localization("Aéroport de Paris-Le Bourget, 93350 Le Bourget", 48.9472, 2.4372),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Counterfeiting Museum",
        description: "Unique museum dedicated to the history and issues of counterfeiting.",
        imagePath: "lib/assets/images/musee_contrefacon.png",
        category: Categories.Museum,
        localization: Localization("16 Rue de la Faisanderie, 75116 Paris", 48.8672, 2.2778),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Fan Museum",
        description: "Small museum specializing in the art and history of fans.",
        imagePath: "lib/assets/images/musee_eventail.png",
        category: Categories.Museum,
        localization: Localization("2 Boulevard de Strasbourg, 75010 Paris", 48.8697, 2.3553),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Police Prefecture Museum",
        description: "Museum dedicated to the history of police and public safety.",
        imagePath: "lib/assets/images/musee_prefecture_police.png",
        category: Categories.Museum,
        localization: Localization("4 Rue de la Montagne Sainte-Geneviève, 75005 Paris", 48.8482, 2.3477),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Arts and Crafts",
        description: "Museum showcasing the history of inventions, technologies, and sciences.",
        imagePath: "lib/assets/images/musee_arts_et_metiers.png",
        category: Categories.Museum,
        localization: Localization("60 Rue Réaumur, 75003 Paris", 48.8670, 2.3582),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Opera Museum",
        description: "Museum dedicated to the history of the Opéra Garnier and lyric art.",
        imagePath: "lib/assets/images/musee_opera.png",
        category: Categories.Museum,
        localization: Localization("8 Rue Scribe, 75009 Paris", 48.8720, 2.3319),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Doll Museum",
        description: "Museum dedicated to dolls and antique toys.",
        imagePath: "lib/assets/images/musee_poupee.png",
        category: Categories.Museum,
        localization: Localization("Impasse Berthaud, 75003 Paris", 48.8601, 2.3539),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cité de la Musique",
        description: "Cultural center dedicated to music, with concerts and exhibitions.",
        imagePath: "lib/assets/images/cite_musique.png",
        category: Categories.Museum,
        localization: Localization("221 Avenue Jean-Jaurès, 75019 Paris", 48.8877, 2.3945),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Chocolate Museum",
        description: "Interactive museum on the history of chocolate and manufacturing techniques.",
        imagePath: "lib/assets/images/musee_chocolat.png",
        category: Categories.Museum,
        localization: Localization("28 Boulevard de Bonne Nouvelle, 75010 Paris", 48.8690, 2.3470),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Military Health",
        description: "Museum presenting the history of military medicine and healthcare in the armed forces.",
        imagePath: "lib/assets/images/musee_sante_armees.png",
        category: Categories.Museum,
        localization: Localization("1 Place Alphonse Laveran, 75005 Paris", 48.8410, 2.3414),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Curie Museum",
        description: "Museum dedicated to the history of Marie Curie's scientific discoveries.",
        imagePath: "lib/assets/images/musee_curie.png",
        category: Categories.Museum,
        localization: Localization("1 Rue Pierre et Marie Curie, 75005 Paris", 48.8447, 2.3449),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Luxembourg Museum",
        description: "Museum exhibiting classical and modern art works.",
        imagePath: "lib/assets/images/musee_luxembourg.png",
        category: Categories.Museum,
        localization: Localization("19 Rue de Vaugirard, 75006 Paris", 48.8440, 2.3346),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Decorative Arts",
        description: "Museum dedicated to decorative arts and everyday objects.",
        imagePath: "lib/assets/images/musee_arts_decoratifs.png",
        category: Categories.Museum,
        localization: Localization("107 Rue de Rivoli, 75001 Paris", 48.8636, 2.3350),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Petit Palais Museum",
        description: "Museum housing a collection of 19th-century art.",
        imagePath: "lib/assets/images/musee_petit_palais.png",
        category: Categories.Museum,
        localization: Localization("Avenue Winston Churchill, 75008 Paris", 48.8664, 2.3122),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Architecture and Heritage",
        description: "Museum showcasing the architecture and heritage of France.",
        imagePath: "lib/assets/images/musee_architecture_patrimoine.png",
        category: Categories.Museum,
        localization: Localization("1 Place du Trocadéro et du 11 Novembre, 75116 Paris", 48.8637, 2.2901),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Police Museum",
        description: "Museum dedicated to the history of police through the centuries.",
        imagePath: "lib/assets/images/musee_prefecture_police.png",
        category: Categories.Museum,
        localization: Localization("4 Rue de la Montagne Sainte-Geneviève, 75005 Paris", 48.8482, 2.3477),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Cernuschi Museum",
        description: "Museum of Asian Arts of the City of Paris.",
        imagePath: "lib/assets/images/musee_cernuschi.png",
        category: Categories.Museum,
        localization: Localization("7 Avenue Velasquez, 75008 Paris", 48.8794, 2.3122),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Romantic Life",
        description: "House-museum dedicated to the Romantic era of the 19th century.",
        imagePath: "lib/assets/images/musee_vie_romantique.png",
        category: Categories.Museum,
        localization: Localization("16 Rue Chaptal, 75009 Paris", 48.8822, 2.3279),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Carnavalet Museum",
        description: "Museum of the history of Paris, from prehistory to the present day.",
        imagePath: "lib/assets/images/musee_carnavalet.png",
        category: Categories.Museum,
        localization: Localization("23 Rue de Sévigné, 75003 Paris", 48.8570, 2.3624),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Montmartre Museum",
        description: "Museum dedicated to the history and culture of the Montmartre district.",
        imagePath: "lib/assets/images/musee_montmartre.png",
        category: Categories.Museum,
        localization: Localization("12 Rue Cortot, 75018 Paris", 48.8876, 2.3384),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Museum of Man",
        description: "Anthropology museum located in the Palais de Chaillot.",
        imagePath: "lib/assets/images/musee_homme.png",
        category: Categories.Museum,
        localization: Localization("17 Place du Trocadéro, 75116 Paris", 48.8619, 2.2867),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Eugène Delacroix National Museum",
        description: "Museum dedicated to painter Eugène Delacroix.",
        imagePath: "lib/assets/images/musee_eugene_delacroix.png",
        category: Categories.Museum,
        localization: Localization("6 Rue de Furstenberg, 75006 Paris", 48.8547, 2.3344),
        schedule: null,
        contact: null,
        website: null,
      ),
      Location(
        nom: "Gustave Moreau National Museum",
        description: "Museum dedicated to the work of symbolist painter Gustave Moreau.",
        imagePath: "lib/assets/images/musee_gustave_moreau.png",
        category: Categories.Museum,
        localization: Localization("14 Rue de la Rochefoucauld, 75009 Paris", 48.8788, 2.3337),
        schedule: null,
        contact: null,
        website: null,
      ),
    ];

    return locations;
  }
}